name: decision-transformer-gym
channels:
- pytorch
dependencies:
- python=3.8.5
- anaconda
- cudatoolkit=10.
- numpy
- pip
- pip:
  - gym==0.22.0
  - mujoco-py==2.0.2.10
  - numpy==1.20.3
  - torch==1.8.1
  - packaging==21.3
  - transformers==4.5.1
  - wandb==0.9.1
